default:
	- rm -rf dist/
	webpack  --display-error-details --config webpack.config.js
	open app.html


setup:
	npm init -y
	npm install jquery --save
	npm install jquery-ui --save
	npm install boostrap --save
	npm install webpack --save




